# Generated by Django 4.0.2 on 2022-05-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0005_inventoryitem_delete_customer_and_more'),
        ('warehouse_manager', '0002_warehouseinventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_manager.inventoryitem'),
        ),
    ]
