# Generated by Django 4.0.2 on 2022-05-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager', '0003_alter_warehouseinventoryitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseinventoryitem',
            old_name='warehouse_inventory',
            new_name='quantity',
        ),
    ]
