# Generated by Django 4.0.2 on 2022-05-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Base_Inventory_Item',
        ),
    ]
