# Generated by Django 4.0.2 on 2022-05-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse_manager', '0003_alter_warehouseinventoryitem_item'),
        ('inventory_manager', '0005_inventoryitem_delete_customer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItem',
            new_name='BasicProduct',
        ),
    ]
