# Generated by Django 4.0.2 on 2022-05-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0006_rename_inventoryitem_basicproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicproduct',
            name='quantity',
        ),
    ]
